### ISSUE TITLE
Warning: Unexpected input(s) 'exit_type'

### ISSUE THREAD

**Issue by yannickm95** [mheap/github-action-required-labels#29]
Hi! When I try to use `v2` of the action which should support exit_type, I get a warning that `exit_type` is not a supported input of the action.
 
> Warning: Unexpected input(s) 'exit_type', valid inputs are ['labels', 'mode', 'count']

The sha that the workflow shows for the action points to the latest release too `48a61a5cb9f36755e6bfe778fd517022f048ef8f`.

```yml
name: Pull Request Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: minimum
          count: 1
          labels: "bug, dependencies, docs, feature, refactor, security, testing"
          exit_type: neutral
```

This is the current workflow setup if that is of any help.

**Comment by tannerbaum** [comment]
@yannickm95 good idea, let's hope that's it. Looks plausible.

**Comment by mheap** [comment]
I definitely missed updating `action.yml`. Thanks for the PR, and I've just released v2.0.1 which your `@v2` line will automatically update to. The error should disappear for any future runs

**Comment by moritzjacobs** [comment]
The error went away but it still isn't doing what I thought it should...?

Result:

<img width="854" alt="Bildschirmfoto 2022-06-23 um 07 43 46" src="https://user-images.githubusercontent.com/2290460/175224216-ebee8a0b-03f0-49c5-9034-16cd351e2a36.png">

Run:

<img width="928" alt="Bildschirmfoto 2022-06-23 um 07 43 04" src="https://user-images.githubusercontent.com/2290460/175224222-bdb7885b-3a21-41e7-b668-901c74f544fe.png">

```yaml
name: Pull Request

on:
  pull_request:
    types: [labeled, ready_for_review, opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    needs: [no-draft]
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "run-chromatic"
          exit_type: neutral
```

Thanks for your help @mheap !

**Comment by mheap** [comment]
@moritzjacobs So, `neutral` is something that used to be a thing but isn't any more. It sets the exit code to be `78` but it was removed (see https://twitter.com/ethomson/status/1163899559279497217)

I guess a way around this is for the action to set an output that can be used in an `if` condition in later steps. So the `exit_type` would be success, then `steps.your-step.outputs.status` would be `failure`.

**Comment by moritzjacobs** [comment]
Ah I see, @mheap thank you for your clarifications!

**Comment by mheap** [comment]
Closing the loop, this was released in #32
